// Cada pregunta tiene:
// - id: identificador ESTABLE (no cambia aunque se reordene el array). Lo usa
//   triviaStore.js para llevar el historial de qué preguntas ya respondió cada
//   usuario — si se usara el índice del array en su lugar, agregar/sacar una
//   pregunta del medio correría los índices y arruinaría el historial guardado.
// - difficulty: 'facil' | 'medio' | 'dificil' (informativo por ahora, no se usa
//   todavía para nada automático, pero queda listo si algún día se quiere pesar
//   la selección o agregar un filtro de dificultad).
export default [
  { id: 1, difficulty: 'facil', question: '¿Cuál es la capital de Australia?', options: ['Sídney', 'Melbourne', 'Canberra', 'Brisbane'], correct: 2 },
  { id: 2, difficulty: 'facil', question: '¿Quién pintó la Mona Lisa?', options: ['Vincent van Gogh', 'Leonardo da Vinci', 'Pablo Picasso', 'Miguel Ángel'], correct: 1 },
  { id: 3, difficulty: 'facil', question: '¿Cuál es el planeta más grande del sistema solar?', options: ['Saturno', 'Júpiter', 'Neptuno', 'Urano'], correct: 1 },
  { id: 4, difficulty: 'medio', question: '¿En qué año llegó el ser humano a la Luna por primera vez?', options: ['1965', '1967', '1969', '1972'], correct: 2 },
  { id: 5, difficulty: 'medio', question: '¿Cuál es el río más largo de Sudamérica?', options: ['Río de la Plata', 'Amazonas', 'Paraná', 'Orinoco'], correct: 1 },
  { id: 6, difficulty: 'medio', question: '¿Qué elemento químico tiene el símbolo Au?', options: ['Plata', 'Oro', 'Cobre', 'Aluminio'], correct: 1 },
  { id: 7, difficulty: 'facil', question: '¿Cuál es el país más grande del mundo por superficie?', options: ['China', 'Canadá', 'Estados Unidos', 'Rusia'], correct: 3 },
  { id: 8, difficulty: 'facil', question: '¿Cuántos jugadores tiene un equipo de fútbol en el campo al comenzar un partido?', options: ['9', '10', '11', '12'], correct: 2 },
  { id: 9, difficulty: 'facil', question: '¿Qué órgano del cuerpo humano se encarga principalmente de bombear la sangre?', options: ['Pulmón', 'Corazón', 'Hígado', 'Riñón'], correct: 1 },
  { id: 10, difficulty: 'medio', question: '¿Cuál es el idioma con más hablantes nativos del mundo?', options: ['Inglés', 'Español', 'Chino mandarín', 'Hindi'], correct: 2 },
  { id: 11, difficulty: 'facil', question: '¿Quién escribió "Don Quijote de la Mancha"?', options: ['Gabriel García Márquez', 'Miguel de Cervantes', 'Jorge Luis Borges', 'Pablo Neruda'], correct: 1 },
  { id: 12, difficulty: 'facil', question: '¿Cuál es el océano más grande del planeta?', options: ['Atlántico', 'Índico', 'Pacífico', 'Ártico'], correct: 2 },
  { id: 13, difficulty: 'facil', question: '¿Qué país ganó el Mundial de Fútbol de 2022?', options: ['Francia', 'Brasil', 'Argentina', 'Croacia'], correct: 2 },
  { id: 14, difficulty: 'facil', question: '¿Cuál es el símbolo químico del oxígeno?', options: ['Ox', 'O', 'Og', 'X'], correct: 1 },
  { id: 15, difficulty: 'facil', question: '¿Cuántos lados tiene un octágono?', options: ['6', '7', '8', '10'], correct: 2 },
  { id: 16, difficulty: 'facil', question: '¿Qué planeta es conocido como el planeta rojo?', options: ['Venus', 'Marte', 'Mercurio', 'Saturno'], correct: 1 },
  { id: 17, difficulty: 'medio', question: '¿Quién compuso la Novena Sinfonía?', options: ['Mozart', 'Beethoven', 'Bach', 'Chopin'], correct: 1 },
  { id: 18, difficulty: 'facil', question: '¿Cuál es la capital de Japón?', options: ['Kioto', 'Osaka', 'Tokio', 'Hiroshima'], correct: 2 },
  { id: 19, difficulty: 'medio', question: '¿Qué animal es el más grande que existe actualmente?', options: ['Elefante africano', 'Ballena azul', 'Tiburón ballena', 'Jirafa'], correct: 1 },
  { id: 20, difficulty: 'facil', question: '¿Cuánto es 12 × 12?', options: ['124', '132', '144', '156'], correct: 2 },
  { id: 21, difficulty: 'facil', question: '¿En qué continente se encuentra Egipto?', options: ['Asia', 'África', 'Europa', 'Oceanía'], correct: 1 },
  { id: 22, difficulty: 'facil', question: '¿Qué científico desarrolló la teoría de la relatividad?', options: ['Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Nikola Tesla'], correct: 1 },
  { id: 23, difficulty: 'facil', question: '¿Cuál es la moneda oficial del Reino Unido?', options: ['Euro', 'Libra esterlina', 'Dólar', 'Franco'], correct: 1 },
  { id: 24, difficulty: 'medio', question: '¿Qué videojuego fue desarrollado originalmente por Mojang?', options: ['Terraria', 'Minecraft', 'Roblox', 'Fortnite'], correct: 1 },
  { id: 25, difficulty: 'facil', question: '¿Cuál es la montaña más alta del mundo sobre el nivel del mar?', options: ['K2', 'Monte Everest', 'Aconcagua', 'Mont Blanc'], correct: 1 },
  { id: 26, difficulty: 'facil', question: '¿Qué país tiene forma aproximada de una bota?', options: ['España', 'Italia', 'Grecia', 'Portugal'], correct: 1 },
  { id: 27, difficulty: 'medio', question: '¿Cuántos huesos tiene aproximadamente un adulto?', options: ['186', '206', '226', '246'], correct: 1 },
  { id: 28, difficulty: 'medio', question: '¿Qué gas es el más abundante en la atmósfera terrestre?', options: ['Oxígeno', 'Nitrógeno', 'Dióxido de carbono', 'Hidrógeno'], correct: 1 },
  { id: 29, difficulty: 'facil', question: '¿Quién fue el primer presidente de los Estados Unidos?', options: ['Abraham Lincoln', 'George Washington', 'Thomas Jefferson', 'John Adams'], correct: 1 },
  { id: 30, difficulty: 'facil', question: '¿Cuál es la capital de Argentina?', options: ['Córdoba', 'Rosario', 'Buenos Aires', 'La Plata'], correct: 2 },
  { id: 31, difficulty: 'medio', question: '¿Qué instrumento musical tiene normalmente 88 teclas?', options: ['Órgano', 'Piano', 'Acordeón', 'Clavecín'], correct: 1 },
  { id: 32, difficulty: 'facil', question: '¿Cuál es el resultado de 144 ÷ 12?', options: ['10', '12', '14', '16'], correct: 1 },
  { id: 33, difficulty: 'medio', question: '¿Qué país inventó los Juegos Olímpicos antiguos?', options: ['Italia', 'Grecia', 'Egipto', 'Turquía'], correct: 1 },
  { id: 34, difficulty: 'medio', question: '¿Cuál es el metal cuyo símbolo químico es Fe?', options: ['Flúor', 'Hierro', 'Fósforo', 'Francio'], correct: 1 },
  { id: 35, difficulty: 'dificil', question: '¿Qué película ganó el Óscar a Mejor Película en 1998?', options: ['Titanic', 'Gladiator', 'Salvar al soldado Ryan', 'La vida es bella'], correct: 0 },
  { id: 36, difficulty: 'medio', question: '¿Cuál es el desierto cálido más grande del mundo?', options: ['Gobi', 'Sahara', 'Atacama', 'Kalahari'], correct: 1 },
  { id: 37, difficulty: 'medio', question: '¿Qué deporte utiliza términos como "birdie", "eagle" y "bogey"?', options: ['Tenis', 'Golf', 'Béisbol', 'Rugby'], correct: 1 },
  { id: 38, difficulty: 'medio', question: '¿Cuál es el órgano más grande del cuerpo humano?', options: ['Hígado', 'Cerebro', 'Piel', 'Pulmón'], correct: 2 },
  { id: 39, difficulty: 'facil', question: '¿Qué empresa creó el sistema operativo Windows?', options: ['Apple', 'Microsoft', 'IBM', 'Google'], correct: 1 },
  { id: 40, difficulty: 'facil', question: '¿Cuántos planetas tiene actualmente reconocido el sistema solar?', options: ['7', '8', '9', '10'], correct: 1 },
  { id: 41, difficulty: 'medio', question: '¿Quién escribió "Cien años de soledad"?', options: ['Julio Cortázar', 'Gabriel García Márquez', 'Mario Vargas Llosa', 'Jorge Luis Borges'], correct: 1 },
  { id: 42, difficulty: 'medio', question: '¿Cuál es la capital de Canadá?', options: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'], correct: 2 },
  { id: 43, difficulty: 'facil', question: '¿Qué selección ganó el Mundial de 2018?', options: ['Alemania', 'Francia', 'Brasil', 'Croacia'], correct: 1 },
  { id: 44, difficulty: 'medio', question: '¿Cuál es el número primo más pequeño?', options: ['0', '1', '2', '3'], correct: 2 },
  { id: 45, difficulty: 'medio', question: '¿Qué científico formuló las tres leyes del movimiento?', options: ['Albert Einstein', 'Isaac Newton', 'Stephen Hawking', 'Galileo Galilei'], correct: 1 },
  { id: 46, difficulty: 'facil', question: '¿Cuál es la capital de Italia?', options: ['Milán', 'Venecia', 'Roma', 'Nápoles'], correct: 2 },
  { id: 47, difficulty: 'facil', question: '¿Qué animal es conocido por cambiar de color para camuflarse?', options: ['Camaleón', 'Canguro', 'Pingüino', 'Delfín'], correct: 0 },
  { id: 48, difficulty: 'medio', question: '¿Cuál es la unidad básica de la vida?', options: ['Átomo', 'Molécula', 'Célula', 'Tejido'], correct: 2 },
  { id: 49, difficulty: 'facil', question: '¿Qué saga de videojuegos tiene personajes como Link y Zelda?', options: ['Final Fantasy', 'The Legend of Zelda', 'Dark Souls', 'Pokémon'], correct: 1 },
  { id: 50, difficulty: 'facil', question: '¿Cuántos segundos hay en 5 minutos?', options: ['250', '300', '350', '400'], correct: 1 },

  // --- Tanda nueva (51-100) ---
  { id: 51, difficulty: 'facil', question: '¿Cuántos continentes se reconocen generalmente?', options: ['5', '6', '7', '8'], correct: 1 },
  { id: 52, difficulty: 'facil', question: '¿Qué color resulta de mezclar azul y amarillo?', options: ['Verde', 'Naranja', 'Morado', 'Rosa'], correct: 0 },
  { id: 53, difficulty: 'facil', question: '¿Cuántas patas tiene una araña?', options: ['6', '8', '10', '4'], correct: 1 },
  { id: 54, difficulty: 'facil', question: '¿En qué país se encuentra la Torre Eiffel?', options: ['Italia', 'España', 'Francia', 'Alemania'], correct: 2 },
  { id: 55, difficulty: 'facil', question: '¿Cuál es el animal terrestre más rápido?', options: ['León', 'Guepardo', 'Caballo', 'Antílope'], correct: 1 },
  { id: 56, difficulty: 'facil', question: '¿Cuál es la capital de España?', options: ['Barcelona', 'Madrid', 'Sevilla', 'Valencia'], correct: 1 },
  { id: 57, difficulty: 'facil', question: '¿Cuál es el planeta más cercano al Sol?', options: ['Venus', 'Tierra', 'Mercurio', 'Marte'], correct: 2 },
  { id: 58, difficulty: 'facil', question: '¿Cuántos días tiene febrero en un año bisiesto?', options: ['28', '29', '30', '31'], correct: 1 },
  { id: 59, difficulty: 'facil', question: '¿Qué instrumento se usa para medir la temperatura?', options: ['Barómetro', 'Termómetro', 'Altímetro', 'Cronómetro'], correct: 1 },
  { id: 60, difficulty: 'facil', question: '¿Cuántos jugadores tiene un equipo de básquet en cancha?', options: ['4', '5', '6', '7'], correct: 1 },
  { id: 61, difficulty: 'facil', question: '¿Cuál es el idioma oficial de Brasil?', options: ['Español', 'Portugués', 'Inglés', 'Francés'], correct: 1 },
  { id: 62, difficulty: 'facil', question: '¿Cuántas cuerdas tiene una guitarra clásica?', options: ['4', '5', '6', '7'], correct: 2 },
  { id: 63, difficulty: 'facil', question: '¿Cuál es la capital de México?', options: ['Guadalajara', 'Monterrey', 'Ciudad de México', 'Cancún'], correct: 2 },
  { id: 64, difficulty: 'facil', question: '¿Qué gas respiramos principalmente para vivir?', options: ['Nitrógeno', 'Oxígeno', 'Dióxido de carbono', 'Hidrógeno'], correct: 1 },
  { id: 65, difficulty: 'facil', question: '¿Cuál es el país más poblado de Sudamérica?', options: ['Argentina', 'Brasil', 'Colombia', 'Perú'], correct: 1 },
  { id: 66, difficulty: 'facil', question: '¿Qué figura geométrica tiene tres lados?', options: ['Cuadrado', 'Triángulo', 'Círculo', 'Pentágono'], correct: 1 },
  { id: 67, difficulty: 'facil', question: '¿Cuál es el deporte más popular del mundo?', options: ['Baloncesto', 'Fútbol', 'Tenis', 'Béisbol'], correct: 1 },
  { id: 68, difficulty: 'medio', question: '¿Qué país tiene actualmente la mayor población del mundo?', options: ['China', 'India', 'Estados Unidos', 'Indonesia'], correct: 1 },
  { id: 69, difficulty: 'medio', question: '¿En qué año cayó el Muro de Berlín?', options: ['1987', '1989', '1991', '1993'], correct: 1 },
  { id: 70, difficulty: 'medio', question: '¿Cuál es el hueso más largo del cuerpo humano?', options: ['Fémur', 'Tibia', 'Húmero', 'Radio'], correct: 0 },
  { id: 71, difficulty: 'medio', question: '¿Qué escritor creó a Sherlock Holmes?', options: ['Agatha Christie', 'Arthur Conan Doyle', 'Edgar Allan Poe', 'Charles Dickens'], correct: 1 },
  { id: 72, difficulty: 'medio', question: '¿Cuál es la velocidad de la luz aproximada en el vacío?', options: ['300.000 km/s', '150.000 km/s', '3.000 km/s', '1.000.000 km/s'], correct: 0 },
  { id: 73, difficulty: 'medio', question: '¿Qué imperio construyó Machu Picchu?', options: ['Azteca', 'Maya', 'Inca', 'Olmeca'], correct: 2 },
  { id: 74, difficulty: 'medio', question: '¿Cuál es la capital de Alemania?', options: ['Múnich', 'Berlín', 'Fráncfort', 'Hamburgo'], correct: 1 },
  { id: 75, difficulty: 'medio', question: '¿Qué pintor es conocido por "La noche estrellada"?', options: ['Pablo Picasso', 'Vincent van Gogh', 'Claude Monet', 'Salvador Dalí'], correct: 1 },
  { id: 76, difficulty: 'medio', question: '¿Qué país tiene más husos horarios, contando sus territorios de ultramar?', options: ['Rusia', 'Estados Unidos', 'Francia', 'China'], correct: 2 },
  { id: 77, difficulty: 'medio', question: '¿Qué elemento químico tiene el número atómico 1?', options: ['Helio', 'Hidrógeno', 'Litio', 'Carbono'], correct: 1 },
  { id: 78, difficulty: 'medio', question: '¿En qué año comenzó la Primera Guerra Mundial?', options: ['1912', '1914', '1918', '1920'], correct: 1 },
  { id: 79, difficulty: 'medio', question: '¿Cuál es el lago más grande del mundo por superficie?', options: ['Lago Superior', 'Mar Caspio', 'Lago Victoria', 'Lago Baikal'], correct: 1 },
  { id: 80, difficulty: 'medio', question: '¿Qué banda británica lanzó el álbum "Abbey Road"?', options: ['The Rolling Stones', 'The Beatles', 'Queen', 'Pink Floyd'], correct: 1 },
  { id: 81, difficulty: 'medio', question: '¿Cuál es la moneda oficial de Japón?', options: ['Yuan', 'Won', 'Yen', 'Baht'], correct: 2 },
  { id: 82, difficulty: 'medio', question: '¿Qué científica ganó dos premios Nobel en categorías distintas?', options: ['Rosalind Franklin', 'Marie Curie', 'Ada Lovelace', 'Jane Goodall'], correct: 1 },
  { id: 83, difficulty: 'medio', question: '¿Cuál es el punto más profundo de los océanos?', options: ['Fosa de Puerto Rico', 'Fosa de las Marianas', 'Fosa de Japón', 'Fosa de Tonga'], correct: 1 },
  { id: 84, difficulty: 'medio', question: '¿En qué región se acuñó la primera moneda como forma de pago?', options: ['China', 'Grecia', 'Lidia (actual Turquía)', 'Egipto'], correct: 2 },
  { id: 85, difficulty: 'dificil', question: '¿Cuál es la capital de Kazajistán?', options: ['Almaty', 'Astaná', 'Bishkek', 'Tashkent'], correct: 1 },
  { id: 86, difficulty: 'dificil', question: '¿Quién escribió "Crimen y castigo"?', options: ['León Tolstói', 'Fiódor Dostoyevski', 'Antón Chéjov', 'Iván Turguénev'], correct: 1 },
  { id: 87, difficulty: 'dificil', question: '¿Cuál es el hueso más pequeño del cuerpo humano?', options: ['Estribo (oído)', 'Falange', 'Rótula', 'Clavícula'], correct: 0 },
  { id: 88, difficulty: 'dificil', question: '¿En qué año se fundó la ONU?', options: ['1942', '1945', '1948', '1950'], correct: 1 },
  { id: 89, difficulty: 'dificil', question: '¿Qué tratado puso fin oficialmente a la Primera Guerra Mundial?', options: ['Tratado de Versalles', 'Tratado de Yalta', 'Tratado de Utrecht', 'Tratado de Tordesillas'], correct: 0 },
  { id: 90, difficulty: 'dificil', question: '¿Cuál es la capital de Mongolia?', options: ['Ulán Bator', 'Astaná', 'Bishkek', 'Tashkent'], correct: 0 },
  { id: 91, difficulty: 'dificil', question: '¿Qué compositor quedó completamente sordo antes de morir?', options: ['Mozart', 'Beethoven', 'Bach', 'Chopin'], correct: 1 },
  { id: 92, difficulty: 'dificil', question: '¿Cuál es el elemento químico más abundante en el universo?', options: ['Oxígeno', 'Helio', 'Hidrógeno', 'Carbono'], correct: 2 },
  { id: 93, difficulty: 'dificil', question: '¿Qué faraón egipcio es famoso por su máscara funeraria de oro?', options: ['Ramsés II', 'Tutankamón', 'Akenatón', 'Keops'], correct: 1 },
  { id: 94, difficulty: 'dificil', question: '¿Cuál es el río más caudaloso del mundo por volumen de agua?', options: ['Nilo', 'Amazonas', 'Misisipi', 'Yangtsé'], correct: 1 },
  { id: 95, difficulty: 'dificil', question: '¿Qué filósofo griego fue maestro de Alejandro Magno?', options: ['Sócrates', 'Platón', 'Aristóteles', 'Pitágoras'], correct: 2 },
  { id: 96, difficulty: 'dificil', question: '¿En qué año se independizó Argentina?', options: ['1810', '1816', '1820', '1825'], correct: 1 },
  { id: 97, difficulty: 'dificil', question: '¿Qué científico propuso la tabla periódica moderna?', options: ['Antoine Lavoisier', 'Dmitri Mendeléyev', 'Marie Curie', 'Ernest Rutherford'], correct: 1 },
  { id: 98, difficulty: 'dificil', question: '¿Cuál es la capital de Bután?', options: ['Timbu', 'Katmandú', 'Dhaka', 'Naipyidó'], correct: 0 },
  { id: 99, difficulty: 'dificil', question: '¿Qué imperio fue gobernado por Gengis Kan?', options: ['Imperio Otomano', 'Imperio Mongol', 'Imperio Persa', 'Imperio Bizantino'], correct: 1 },
  { id: 100, difficulty: 'dificil', question: '¿Cuál es la partícula subatómica con carga negativa?', options: ['Protón', 'Neutrón', 'Electrón', 'Positrón'], correct: 2 },
];
